apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
  name: omiireplica-set
  labels:
    app: omii
spec:
    selector: 
      matchExpressions:      
         #-  { key: app, operator: In , values: [rsapp,  new-app]}
         -  { key: app, operator: In , values: [omii, new-app]}
    #matchLabels: 
          #app: rsapp
    replicas: 5
    template:
      metadata:
        labels:
          name: nginxapp
          app: omii
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
