apiVersion: v1
kind: Service
metadata:
  name: nodeportsvc
spec:
  selector:
    app: new-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx

  
    

